/**
 * Script to seed players to Firestore
 * Run with: npx tsx scripts/seedPlayers.ts
 */

import { initializeApp } from 'firebase/app'
import { getFirestore, collection, doc, writeBatch, serverTimestamp } from 'firebase/firestore'

// Firebase config
const firebaseConfig = {
  apiKey: "AIzaSyBxgs08wKUXezywoWMwDZDIVC0vgMX6M60",
  authDomain: "fiveaside-8baa0.firebaseapp.com",
  projectId: "fiveaside-8baa0",
  storageBucket: "fiveaside-8baa0.firebasestorage.app",
  messagingSenderId: "143373610114",
  appId: "1:143373610114:web:8663854cc35d8b5d2f589b",
  measurementId: "G-YVBZ2D0HDK"
}

// Initialize Firebase
const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

// Player data extracted from new_version.html
const modernPlayers = [
  { name: "ERLING HAALAND", hint: "Norwegian striker who plays for Manchester City and broke the Premier League scoring record in his debut season" },
  { name: "BENJAMIN SESKO", hint: "Slovenian striker who joined Manchester United from RB Leipzig." },
  { name: "MARTIN ZUBIMENDI", hint: "Spanish midfielder who joined Arsenal from Real Sociedad. Deep-lying playmaker and Spain international" },
  { name: "VIKTOR GYOKERES", hint: "Swedish striker who joined Arsenal from Sporting." },
  { name: "EBERECHI EZE", hint: "English attacking midfielder who joined Arsenal from Crystal Palace after winning the FA Cup." },
  { name: "FLORIAN WIRTZ", hint: "German attacking midfielder who joined Liverpool from Bayer Leverkusen." },
  { name: "JEREMY FRIMPONG", hint: "Dutch right-back who joined Liverpool from Bayer Leverkusen" },
  { name: "LIAM DELAP", hint: "English striker who joined Chelsea from Ipswich Town." },
  { name: "JOAO PEDRO", hint: "Brazilian forward who joined Chelsea from Brighton." },
  { name: "ALEJANDRO GARNACHO", hint: "Argentine winger who joined Chelsea from Manchester United." },
  { name: "ESTEVAO", hint: "Brazilian winger who joined Chelsea from Palmeiras." },
  { name: "DOMINIC CALVERT-LEWIN", hint: "English striker who joined Leeds United from Everton." },
  { name: "MATHEUS CUNHA", hint: "Brazilian attacking midfielder who joined Manchester United from Wolves." },
  { name: "BRYAN MBEUMO", hint: "Cameroonian winger who joined Manchester United from Brentford." },
  { name: "MATHYS TEL", hint: "French forward who joined Tottenham from Bayern Munich." },
  { name: "MATEUS FERNANDES", hint: "Portuguese midfielder who joined West Ham from Southampton." },
  { name: "JORGEN STRAND LARSEN", hint: "Norwegian striker who joined Wolves permanently from Celta Vigo." },
  { name: "GIANLUIGI DONNARUMMA", hint: "Italian goalkeeper who joined Manchester City from PSG after winning the Champions League." },
  { name: "TIJJANI REIJNDERS", hint: "Dutch midfielder who joined Manchester City from AC Milan." },
  { name: "JAMES MILNER", hint: "English midfielder who played for Leeds United, Newcastle United, Aston Villa, Manchester City and Liverpool before joining Brighton." },
  { name: "RAYAN CHERKI", hint: "French attacking midfielder who joined Manchester City from Lyon." },
  { name: "JAMES MCATEE", hint: "English attacking midfielder who joined Nottingham Forest from Manchester City." },
  { name: "DOUGLAS LUIZ", hint: "Brazilian midfielder on loan at Nottingham Forest from Juventus. Used to play for Aston Villa" },
  { name: "DAN NDOYE", hint: "Swiss winger who joined Nottingham Forest from Bologna." },
  { name: "ARNAUD KALIMUENDO", hint: "French striker who joined Nottingham Forest from Rennes." },
  { name: "JORDAN HENDERSON", hint: "English midfielder who joined Brentford from Ajax. Former Liverpool captain" },
  { name: "DANGO OUATTARA", hint: "Burkina Faso winger who joined Brentford from Bournemouth." },
  { name: "CAOIMHIN KELLEHER", hint: "Irish goalkeeper who joined Brentford from Liverpool." },
  { name: "KIERNAN DEWSBURY-HALL", hint: "English midfielder who joined Everton from Chelsea. Used to play for Leicester City" },
  { name: "TYLER DIBLING", hint: "English winger who joined Everton from Southampton." },
  { name: "YEREMY PINO", hint: "Spanish winger who joined Crystal Palace from Villarreal." },
  { name: "MOHAMMED KUDUS", hint: "Ghanaian attacking midfielder who joined Tottenham from West Ham." },
  { name: "CALLUM WILSON", hint: "English striker who joined West Ham from Newcastle." },
  { name: "JEAN-CLAIR TODIBO", hint: "French centre-back who joined West Ham from Nice." },
  { name: "KYLE WALKER-PETERS", hint: "English full-back who joined West Ham from Southampton." },
  { name: "ANTHONY ELANGA", hint: "Swedish winger who joined Newcastle from Nottingham Forest." },
  { name: "NICK WOLTEMADE", hint: "German striker who joined Newcastle from Stuttgart for a club record fee." },
  { name: "MALICK THIAW", hint: "German centre-back who joined Newcastle from AC Milan." },
  { name: "AARON RAMSDALE", hint: "English goalkeeper on loan at Newcastle from Southampton." },
  { name: "HUGO EKITIKE", hint: "French forward who joined Liverpool from Eintracht Frankfurt" },
  { name: "MOHAMED SALAH", hint: "Egyptian winger who plays for Liverpool and has won the Premier League Golden Boot three times" },
  { name: "XAVI SIMONS", hint: "Dutch attacking midfielder who joined Tottenham from RB Leipzig" },
  { name: "JOAO PALHINHA", hint: "Portuguese defensive midfielder on loan at Tottenham from Bayern Munich." },
  { name: "RANDAL KOLO MUANI", hint: "French forward who joined Tottenham on loan from Juventus" },
  { name: "BRUNO FERNANDES", hint: "Portuguese midfielder who captains Manchester United and joined from Sporting CP" },
  { name: "JOACHIM ANDERSEN", hint: "Danish center-back who plays for Fulham after moving from Crystal Palace" },
  { name: "MARC GUEHI", hint: "English center-back who captains Crystal Palace and came through Chelsea's academy" },
  { name: "JACK GREALISH", hint: "English winger who is at Everton on loan. Previously played for Aston Villa and Manchester City" },
  { name: "BUKAYO SAKA", hint: "English winger who came through Arsenal's Hale End academy and wears number 7" },
  { name: "VIRGIL VAN DIJK", hint: "Dutch center-back who captains Liverpool and joined from Southampton" },
  { name: "OMARI HUTCHINSON", hint: "English winger who moved to Nottingham Forest from Ipswich Town for a club record fee" },
  { name: "MURILLO", hint: "Brazilian center-back who plays for Nottingham Forest." },
  { name: "CALLUM HUDSON-ODOI", hint: "English winger who plays for Nottingham Forest. Signed from Chelsea. Scored the winner at Anfield" },
  { name: "EMILE SMITH ROWE", hint: "English attacking midfielder who plays for Fulham after moving from Arsenal" },
  { name: "RAHEEM STERLING", hint: "English winger who plays for Chelsea. Previously played for Liverpool and Manchester City" },
  { name: "PHIL FODEN", hint: "Young English midfielder who plays for Manchester City. Premier League player of the season 2023-24" },
  { name: "GABRIEL JESUS", hint: "Brazilian forward who moved from Manchester City to Arsenal" },
  { name: "GABRIEL", hint: "Brazilian defender who joined Arsenal from Lille" },
  { name: "RUBEN DIAS", hint: "Portuguese defender who won the FWA Footballer of the Year in his debut Premier League season" },
  { name: "ANDY ROBERTSON", hint: "Liverpool's Scottish left-back known for his consistent performances and assists" },
  { name: "MASON MOUNT", hint: "English midfielder who came through Chelsea's academy and now plays for Manchester United" },
  { name: "DECLAN RICE", hint: "English defensive midfielder who captained West Ham before a big move to Arsenal" },
  { name: "JAMES MADDISON", hint: "English attacking midfielder known for his creativity and set-pieces. Moved from Leicester to Tottenham" },
  { name: "KIERAN TRIPPIER", hint: "English right-back who returned to the Premier League after a spell in Spain with Atletico Madrid" },
  { name: "OLLIE WATKINS", hint: "Aston Villa striker who made the jump from Championship to Premier League after joining from Brentford" },
  { name: "JAMES WARD-PROWSE", hint: "English midfielder renowned for his exceptional free-kick ability. Moved from Southampton to West Ham" },
  { name: "GABRIEL MARTINELLI", hint: "Brazilian winger who joined Arsenal as a teenager" },
  { name: "MARTIN ODEGAARD", hint: "Norwegian midfielder who became Arsenal's youngest captain after joining from Real Madrid" },
  { name: "REECE JAMES", hint: "English right-back who emerged from Chelsea's academy" },
  { name: "RODRI", hint: "Spanish defensive midfielder who won the balon d'or. Plays for Manchester City" },
  { name: "BERNARDO SILVA", hint: "Manchester City's Portuguese midfielder known for his technical skills and work rate" },
  { name: "ALISSON BECKER", hint: "Brazilian goalkeeper who scored a crucial header for Liverpool" },
  { name: "ANTHONY GORDON", hint: "English winger who moved from Everton to Newcastle United." },
  { name: "COLE PALMER", hint: "Young English forward who plays for Chelsea after joining from Manchester City" },
  { name: "JOHN MCGINN", hint: "Scottish midfielder who helped Aston Villa return to the Premier League. " },
  { name: "DANNY WELBECK", hint: "English forward who has played for Manchester United, Arsenal, and Brighton" },
  { name: "WILLIAM SALIBA", hint: "French defender who joined Arsenal from Saint-Etienne" },
  { name: "DOMINIC SOLANKE", hint: "English striker who found his form after moving to Bournemouth from Liverpool. Now plays for Tottenham" },
  { name: "DOMINIK SZOBOSZLAI", hint: "Hungarian midfielder who joined Liverpool from RB Leipzig" },
  { name: "JEREMY DOKU", hint: "Belgian winger who joined Manchester City from Rennes" },
  { name: "ALEXANDER ISAK", hint: "Swedish striker who moved to Liverpool from Newcastle United for a Premier League record fee" },
  { name: "MORGAN RODGERS", hint: "English midfielder who signed for Aston Villa from Middlesbrough" },
  { name: "JARROD BOWEN", hint: "English winger who made the jump from Championship to Premier League with West Ham" },
  { name: "PEDRO NETO", hint: "Portuguese winger who became a key player for Wolves before joining Chelsea" },
  { name: "DAVID RAYA", hint: "Spanish goalkeeper who joined Arsenal from Brentford" },
  { name: "SAVINHO", hint: "Brazilian winger who joined Manchester City from Troyes after a good season on loan at Girona" },
  { name: "MATTY CASH", hint: "English right-back who plays for Poland. joined Aston Villa from Nottingham Forest" },
  { name: "JAMES TARKOWSKI", hint: "English defender who was a mainstay for Burnley before joining Everton" },
  { name: "KOBBIE MAINOO", hint: "English midfielder who broke into the Manchester United first team. Scored in the FA Cup final" },
  { name: "RICHARLISON", hint: "Brazilian forward who played for Watford and Everton before joining Tottenham" },
  { name: "CURTIS JONES", hint: "English midfielder who came through Liverpool's academy" },
  { name: "IBRAHIMA KONATE", hint: "French defender who joined Liverpool from RB Leipzig" },
  { name: "MICKY VAN DE VEN", hint: "Dutch defender who joined Tottenham and impressed with his speed" },
  { name: "HARRY MAGUIRE", hint: "English defender who became Manchester United's captain after joining from Leicester" },
  { name: "JACOB RAMSEY", hint: "English midfielder who broke into the Aston Villa first team now plays for Newcastle United" },
  { name: "YANKUBA MINTEH", hint: "Gambian who joined Brighton from Newcastle United after impressing at Feyenoord on loan" },
  { name: "MORGAN GIBBS-WHITE", hint: "English midfielder who made a big-money move to Nottingham Forest" },
  { name: "MILOS KIRKEZ", hint: "Left back who joined Liverpool from Bournemouth" },
  { name: "BRENNAN JOHNSON", hint: "Welsh forward who helped Nottingham Forest return to the Premier League before joining Tottenham. Scored the winner in the Europa League final" },
  { name: "MAX KILMAN", hint: "Defender who joined West Ham from Wolves for 40 million pounds" },
  { name: "JOSHUA ZIRKZEE", hint: "Dutch striker who joined Manchester United from Bologna" },
  { name: "BEN WHITE", hint: "English defender who established himself at Arsenal for his versatility and tackling." },
  { name: "OLEKSANDR ZINCHENKO", hint: "Ukrainian defender who joined Arsenal from Manchester City. Now at Nottingham Forest" },
  { name: "EMILIANO MARTINEZ", hint: "Argentinian goalkeeper who won the World Cup." },
  { name: "MIKKEL DAMSGAARD", hint: "Danish midfielder who joined Brentford after impressing in the Euro 2020 tournament." },
  { name: "MAX DOWMAN", hint: "Made his premier league debut for Arsenal aged 15 years old." },
  { name: "CHRISTIAN NORGAARD", hint: "Danish midfielder who played a key role in Brentford's promotion to the Premier League before moving to Arsenal." },
  { name: "LEWIS DUNK", hint: "English defender who has been a mainstay for Brighton and the national team." },
  { name: "SOLLY MARCH", hint: "English midfielder who became a regular starter for Brighton, known for his dribbling." },
  { name: "KAORU MITOMA", hint: "Japanese forward who joined Brighton and impressed with his speed and dribbling." },
  { name: "MARC CUCURELLA", hint: "Spanish defender who signed with Chelsea from Brighton." },
  { name: "MALO GUSTO", hint: "French defender who joined Chelsea from Lyon." },
  { name: "LEVI COLWILL", hint: "English defender who broke into the Chelsea first team." },
  { name: "ENZO FERNANDEZ", hint: "Argentinian midfielder who joined Chelsea after winning the World Cup." },
  { name: "ANTONY", hint: "Brazilian winger who joined Manchester United from Ajax." },
  { name: "MOISES CAICEDO", hint: "Ecuadorian midfielder who signed with Chelsea from Brighton for a British record fee." },
  { name: "BERND LENO", hint: "German goalkeeper who joined Fulham from Arsenal." },
  { name: "ANTONEE ROBINSON", hint: "American left-back who plays for Fulham." },
  { name: "LUCAS PAQUETA", hint: "Brazilian midfielder who joined West Ham United from Lyon." },
  { name: "DWIGHT MCNEIL", hint: "English winger who joined Everton from Burnley." },
  { name: "ADAM WHARTON", hint: "English midfielder who joined Crystal Palace from Blackburn Rovers." },
  { name: "JAMIE GITTENS", hint: "English winger who joined Chelsea from Borussia Dortmund." },
  { name: "THIERNO BARRY", hint: "French striker who joined Everton from Villarreal." },
  { name: "SAMUEL CHUKWUEZE", hint: "Nigerian winger who joined Fulham on loan from AC Milan." },
  { name: "CHEICK DOUCOURE", hint: "Malian midfielder who joined Crystal Palace from Lens." },
  { name: "KEVIN", hint: "Brazilian winger who joined Fulham from Shakhtar Donetsk." },
  { name: "JAMES JUSTIN", hint: "English right-back who plays for Leeds United after moving from Leicester City." },
  { name: "HARVEY ELLIOTT", hint: "English winger who plays for Aston Villa after moving from Liverpool." },
  { name: "RAYAN AIT-NOURI", hint: "French defender who joined Manchester City from Wolves." },
  { name: "JAMES TOMKINS", hint: "English defender who has been a mainstay for Crystal Palace." },
  { name: "CHRIS WOOD", hint: "New Zealand striker who joined Nottingham Forest from Newcastle after a good spell at Burnley." },
  { name: "RYAN GRAVENBURCH", hint: "Dutch midfielder who joined Liverpool from Bayern Munich." },
  { name: "JORDAN PICKFORD", hint: "English goalkeeper who has tiny arms and plays for Everton." },
  { name: "ILIMAN NDIAYE", hint: "Senegalese midfielder who joined Everton from Marseille." },
  { name: "JOSKO GVARDIOL", hint: "Croatian defender who joined Manchester City from RB Leipzig. Loves a goal." },
  { name: "JAMES GARNER", hint: "English midfielder who joined Everton from Manchester United." },
  { name: "ALEXIS MAC ALLISTER", hint: "Argentinian midfielder who joined Liverpool from Brighton & Hove Albion." },
  { name: "CODY GAKPO", hint: "Dutch forward who joined Liverpool from PSV Eindhoven." },
  { name: "SANDRO TONALI", hint: "Italian midfielder who joined Newcastle United from AC Milan." },
  { name: "HARVEY BARNES", hint: "English winger who joined Newcastle United from Leicester City." },
  { name: "SVEN BOTMAN", hint: "Dutch center-back who is a key player for Newcastle United." },
  { name: "CRISTIAN ROMERO", hint: "Argentinian center-back who is a key player for Tottenham Hotspur." },
  { name: "DEJAN KULUSEVSKI", hint: "Swedish winger who joined Tottenham Hotspur from Juventus." },
  { name: "RICO HENRY", hint: "English left-back who plays for Brentford." },
  { name: "WESLEY FOFANA", hint: "French defender who joined Chelsea from Leicester City." },
  { name: "WILFRIED GNONTO", hint: "Italian winger who plays for Leeds United." },
  { name: "DANIEL JAMES", hint: "Welsh winger who joined Leeds United from Manchester United." },
  { name: "CHRIS RIGG", hint: "Young English midfielder who broke through at Sunderland." },
  { name: "GRANIT XHAKA", hint: "Swiss midfielder and captain who joined Sunderland from Bayer Leverkusen. Former Arsenal captain who won the Bundesliga with Leverkusen." },
  { name: "KYLE WALKER", hint: "English right-back who joined Burnley from Manchester City. Won 17 trophies at City and has over 90 England caps." },
  { name: "LUKAS NMECHA", hint: "German striker who joined Leeds United from Wolfsburg. Former Manchester City academy player who won the U21 Euros with Germany." },
  { name: "ARMANDO BROJA", hint: "Albanian striker who joined Burnley from Chelsea. Promising forward who represents Albania at international level." },
  { name: "LOUM TCHAOUNA", hint: "French winger who joined Burnley from Lazio. Chad-born attacker who came through the Rennes academy system." },
  { name: "NOAH OKAFOR", hint: "Swiss forward who joined Leeds United from AC Milan. Former Red Bull Salzburg star who represents Switzerland internationally." },
  { name: "JAMES TRAFFORD", hint: "English goalkeeper who returned to Manchester City from Burnley. Young keeper who won the U21 Euros with England." },
  { name: "ETHAN NWANERI", hint: "English attacking midfielder at Arsenal. Youngest ever Premier League player when he debuted at 15" },
  { name: "RIO NGUMOHA", hint: "English winger who joined Liverpool from Chelsea academy. Highly-rated young talent" },
]

const legendPlayers = [
  { name: "KEVIN DE BRUYNE", hint: "Belgian midfielder who won 6 Premier League titles with Manchester City before moving to Napoli" },
  { name: "MARCUS RASHFORD", hint: "English forward from Manchester United's academy who moved to Barcelona. Campaigned against child poverty" },
  { name: "EDERSON", hint: "Brazilian goalkeeper who played Manchester City. Known for his distribution skills" },
  { name: "HEUNG MIN SON", hint: "South Korean forward who spent 10 years at Tottenham before moving to LA FC. Shared the Golden Boot with Salah in 2021-22" },
  { name: "ALAN SHEARER", hint: "All-time top scorer in the Premier League. Played for Blackburn and Newcastle" },
  { name: "JAAP STAM", hint: "Dutch defender who was a key player for Manchester United in the 99 treble-winning season" },
  { name: "GIANLUCA VIALLI", hint: "Italian forward who played for Sampdoria, Juventus, and Chelsea" },
  { name: "THIERRY HENRY", hint: "French striker who was part of Arsenal's 'Invincibles'. Arsenal's all-time top scorer" },
  { name: "ERIC CANTONA", hint: "French forward known for his swagger and crucial role in Manchester United's success" },
  { name: "PHILIPPE COUTINHO", hint: "Brazilian midfielder who was a key player for Liverpool before joining Barcelona" },
  { name: "STEVEN GERRARD", hint: "Liverpool midfielder known for his long-range goals and leadership" },
  { name: "FRANK LAMPARD", hint: "Midfielder who became Chelsea's all-time top scorer" },
  { name: "RYAN GIGGS", hint: "Welsh winger who played for Manchester United for over two decades" },
  { name: "PATRICK VIEIRA", hint: "French midfielder who captained Arsenal during their 'Invincibles' season" },
  { name: "ROY KEANE", hint: "Irish midfielder known for his aggressive style and leadership at Manchester United" },
  { name: "PETER SCHMEICHEL", hint: "Danish goalkeeper who was crucial to Manchester United's success in the 90s" },
  { name: "DES WALKER", hint: "English defender known for his pace and strength. Played for Nottingham Forest and Sheffield Wednesday" },
  { name: "EMMANUEL PETIT", hint: "French midfielder who won the World Cup with France and played for Arsenal" },
  { name: "DAVID GINOLA", hint: "French winger known for his flair and skill. Played for Tottenham and Newcastle" },
  { name: "XABI ALONSO", hint: "Spanish midfielder known for his passing range and vision. Played for Liverpool and Real Madrid" },
  { name: "JOHN TERRY", hint: "Chelsea defender who captained the club to multiple Premier League titles" },
  { name: "RIO FERDINAND", hint: "English defender who formed a formidable partnership with Nemanja Vidic" },
  { name: "PAUL SCHOLES", hint: "Manchester United midfielder known for his passing range and shooting ability" },
  { name: "WAYNE ROONEY", hint: "Forward who became Manchester United and England's all-time top scorer" },
  { name: "DIDIER DROGBA", hint: "Ivorian striker known for his physicality and crucial goals for Chelsea" },
  { name: "DENNIS BERGKAMP", hint: "Dutch forward renowned for his technical skill and creativity. Known as the 'Non-Flying Dutchman'" },
  { name: "DAVID BECKHAM", hint: "English midfielder famous for his crossing and free-kick ability" },
  { name: "CRISTIANO RONALDO", hint: "Portuguese forward who won his first Ballon d'Or while at Manchester United" },
  { name: "VINCENT KOMPANY", hint: "Belgian defender who captained Manchester City to multiple titles" },
  { name: "ASHLEY COLE", hint: "English left-back considered one of the best in his position" },
  { name: "NEMANJA VIDIC", hint: "Serbian defender who formed a formidable partnership with Rio Ferdinand" },
  { name: "MICHAEL CARRICK", hint: "English midfielder who played for West Ham, Tottenham and Manchester United known for his passing and vision" },
  { name: "PETER CROUCH", hint: "English striker known for his height and 'robot' goal celebration" },
  { name: "IAN WRIGHT", hint: "English striker who was Arsenal's top scorer before being surpassed by Thierry Henry" },
  { name: "JAMIE CARRAGHER", hint: "Liverpool defender who spent his entire career with the club" },
  { name: "GARY NEVILLE", hint: "Manchester United right-back who was part of the 'Class of 92'" },
  { name: "MICHAEL OWEN", hint: "English striker who won the Ballon d'Or while at Liverpool" },
  { name: "ROBBIE FOWLER", hint: "Liverpool striker nicknamed 'God' by the club's fans" },
  { name: "SERGIO AGUERO", hint: "Argentinian striker who scored the most famous goal in Premier League history" },
  { name: "MATT LE TISSIER", hint: "Southampton midfielder known for his loyalty and spectacular goals" },
  { name: "GIANFRANCO ZOLA", hint: "Italian forward who became a Chelsea legend despite joining later in his career" },
  { name: "EMILE HESKEY", hint: "English striker who formed a successful partnership with Michael Owen" },
  { name: "JIMMY FLOYD HASSELBAINK", hint: "Dutch striker who was a prolific goalscorer for Leeds United and Chelsea" },
  { name: "DUNCAN FERGUSON", hint: "Scottish forward known for his physicality and aerial ability. Nicknamed 'Big Dunc'" },
  { name: "STAN COLLYMORE", hint: "English striker who played for Nottingham Forest, Liverpool, and Aston Villa" },
  { name: "PETER BEARDSLEY", hint: "English forward who played for Liverpool, Newcastle, and Everton" },
  { name: "JURGEN KLINSMANN", hint: "German forward who played for Tottenham and won the World Cup with Germany" },
  { name: "PAULO DI CANIO", hint: "Italian forward remembered for his spectacular goals and controversial moments" },
  { name: "RUUD VAN NISTELROOY", hint: "Dutch striker who was a prolific goalscorer for Manchester United" },
  { name: "EDWIN VAN DER SAR", hint: "Dutch goalkeeper who had a successful late career at Manchester United" },
  { name: "PETR CECH", hint: "Czech goalkeeper who holds the record for most clean sheets in the Premier League" },
  { name: "CLAUDE MAKELELE", hint: "French midfielder who defined the defensive midfield role" },
  { name: "ROBERT PIRES", hint: "French winger who was a key part of Arsenal's 'Invincibles'" },
  { name: "FREDDIE LJUNGBERG", hint: "Swedish midfielder who was part of Arsenal's 'Invincibles'" },
  { name: "SOL CAMPBELL", hint: "English defender who controversially moved from Tottenham to Arsenal" },
  { name: "ANDY COLE", hint: "English striker who is the third-highest goalscorer in Premier League history" },
  { name: "TEDDY SHERINGHAM", hint: "English forward who scored crucial goals for Manchester United in their treble-winning season" },
  { name: "LES FERDINAND", hint: "English striker nicknamed 'Sir Les' who played for several Premier League clubs" },
  { name: "TONY ADAMS", hint: "English defender who captained Arsenal to league titles in three different decades" },
  { name: "CHRIS SUTTON", hint: "Formed the famous 'SAS' strike partnership with Alan Shearer at Blackburn Rovers" },
  { name: "MARK VIDUKA", hint: "Captained Australia at the 2006 World Cup and scored 4 goals against Liverpool in a single match" },
  { name: "LUIS SUAREZ", hint: "Uruguayan striker who won the Premier League Golden Boot with Liverpool before moving to Barcelona" },
  { name: "SAMI HYYPIA", hint: "Finnish defender who captained Liverpool." },
  { name: "MARCEL DESAILLY", hint: "The first player to win the UEFA Champions League with two different clubs" },
  { name: "LUCAS RADEBE", hint: "South African defender and Leeds United legend, nicknamed 'The Chief'" },
  { name: "GARY SPEED", hint: "The first player to reach 500 Premier League appearances. Played for Leeds United, Everton, Newcastle, and Bolton" },
  { name: "NIGEL MARTYN", hint: "The first £1 million goalkeeper in English football. Played for Crystal Palace, Leeds United, and Everton" },
  { name: "GARETH SOUTHGATE", hint: "England manager who played for Crystal Palace, Aston Villa, and Middlesbrough" },
  { name: "TIM FLOWERS", hint: "Blackburn Rovers goalkeeper who won the Premier League in 1995" },
  { name: "GARETH BALE", hint: "Welsh winger who won multiple Champions League titles with Real Madrid after leaving Tottenham" },
  { name: "GARY MCALLISTER", hint: "Scottish midfielder who won the treble with Liverpool in 2001. Scored the best goal ever against Everton" },
  { name: "NICOLAS ANELKA", hint: "French striker who played for Arsenal, Real Madrid, and Chelsea" },
  { name: "DIMITAR BERBATOV", hint: "Bulgarian striker who won the Premier League Golden Boot with Manchester United" },
  { name: "DION DUBLIN", hint: "English striker who scored Premier League goals for Manchester United, Coventry City, Aston Villa and Norwich City." },
  { name: "MARC OVERMARS", hint: "Dutch winger who won the Premier League and FA Cup with Arsenal" },
  { name: "ROBERTO DI MATTEO", hint: "Scored the fastest goal in FA Cup Final history after just 42 seconds for Chelsea" },
  { name: "DAVID BATTY", hint: "English midfield who was part of the Blackburn Rovers team that won the Premier League in 1995" },
  { name: "TONY YEBOAH", hint: "Scored a stunning volley against Wimbledon that won Goal of the Season in 1995-96" },
  { name: "LEDLEY KING", hint: "Tottenham Hotspur legend who played his entire career at the club" },
  { name: "FABRIZIO RAVANELLI", hint: "The 'White Feather' who scored a hat-trick on his Middlesbrough debut" },
  { name: "HARRY KEWELL", hint: "Australian winger who played for Leeds United and Liverpool" },
  { name: "JAY JAY OKOCHA", hint: "Nigerian midfielder known for his skill and flair at Bolton Wanderers" },
  { name: "JUNINHO", hint: "The diminutive Brazilian playmaker who became a Middlesbrough legend" },
  { name: "PATRIK BERGER", hint: "Czech midfielder who was part of the Liverpool team that won the treble in 2001" },
  { name: "DAVID JAMES", hint: "The goalkeeper with the most clean sheets in Premier League history (169)" },
  { name: "STEVE MCMANAMAN", hint: "Won two Champions Leagues and a La Liga title with Real Madrid after leaving Liverpool" },
  { name: "DAMIEN DUFF", hint: "Irish winger who played for Blackburn, Chelsea, and Newcastle in the Premier League" },
  { name: "ARJEN ROBBEN", hint: "Dutch winger who won two Premier League titles with Chelsea" },
  { name: "PATRICE EVRA", hint: "French left-back who won five Premier League titles with Manchester United" },
  { name: "PEPE REINA", hint: "Spanish goalkeeper who kept a record 134 clean sheets for Liverpool" },
  { name: "ROBIN VAN PERSIE", hint: "Dutch striker who won the Premier League with Manchester United in 2013 after leaving Arsenal" },
  { name: "LUKA MODRIC", hint: "Croatian midfielder who won the Ballon d'Or in 2018" },
  { name: "YAYA TOURE", hint: "Ivorian midfielder who won three Premier League titles with Manchester City" },
  { name: "RICARDO CARVALHO", hint: "Portuguese defender who won the Premier League with Chelsea" },
  { name: "STUART PEARCE", hint: "English left-back nicknamed 'Psycho,' who played for Nottingham Forest and captained England." },
  { name: "CARLOS TEVEZ", hint: "Argentine striker who played for both Manchester United and Manchester City" },
  { name: "CESC FABREGAS", hint: "Spanish midfielder who started his career at Arsenal before moving to Barcelona and Chelsea" },
  { name: "BRYAN ROBSON", hint: "English midfielder and one of Manchester United's most iconic captains in the early Premier League years." },
  { name: "NGOLO KANTE", hint: "French midfielder who won back-to-back Premier League titles with Leicester and Chelsea" },
  { name: "JAMIE VARDY", hint: "English striker who won the Premier League with Leicester City in 2016" },
  { name: "FERNANDINHO", hint: "Long-serving defensive midfielder for Manchester City who won multiple Premier League titles" },
  { name: "GILBERTO SILVA", hint: "Brazilian midfielder who was a key part of Arsenal's 'Invincibles'" },
  { name: "JAVIER MASCHERANO", hint: "Argentinian midfielder who played for West Ham and Liverpool" },
  { name: "FERNANDO TORRES", hint: "Spanish striker who won the World Cup and European Championship with Spain. Played for Liverpool and Chelsea" },
  { name: "KOLO TOURE", hint: "Ivorian defender who played for Arsenal and Manchester City" },
  { name: "GARETH BARRY", hint: "English midfielder who holds the record for most Premier League appearances" },
  { name: "MICHAEL BALLACK", hint: "German midfielder who played for Chelsea and Bayern Munich" },
  { name: "RIYAD MAHREZ", hint: "Algerian winger who won the Premier League with both Leicester City and Manchester City" },
  { name: "EDEN HAZARD", hint: "Belgian winger who won the Premier League Player of the Season award in 2015" },
  { name: "JUAN MATA", hint: "Spanish midfielder who has won the Champions League, Europa League, and FA Cup with Chelsea and Manchester United" },
  { name: "CESAR AZPILICUETA", hint: "Versatile Spanish defender who has captained Chelsea to multiple trophies including the Champions League" },
  { name: "MESUT OZIL", hint: "German playmaker who recorded 19 assists in a single Premier League season for Arsenal in 2015-16" },
  { name: "DAVID SILVA", hint: "Spanish midfielder who spent 10 successful years at Manchester City before joining Real Sociedad" },
  { name: "LEIGHTON BAINES", hint: "Long-serving Everton left-back known for his exceptional free-kick ability" },
  { name: "ROMELU LUKAKU", hint: "Belgian striker who has scored over 100 Premier League goals" },
  { name: "DIEGO COSTA", hint: "Controversial Spanish striker who won two Premier League titles with Chelsea" },
  { name: "SADIO MANE", hint: "Senegalese winger who won the Premier League with Liverpool in 2020 and the Champions League in 2019" },
  { name: "PAUL INCE", hint: "English midfielder who captained Manchester United and also played for Liverpool." },
  { name: "HARRY KANE", hint: "England captain and Tottenham's all-time leading goalscorer in the Premier League" },
  { name: "MICHAEL ESSIEN", hint: "Ghanaian midfielder known for his powerful long-range shots at Chelsea" },
  { name: "STEVE BRUCE", hint: "English defender who captained Manchester United to their first Premier League title." },
  { name: "KEVIN PHILLIPS", hint: "The only Englishman to win the European Golden Shoe, scoring 30 goals for Sunderland in 1999/2000." },
  { name: "TIM CAHILL", hint: "Australian midfielder renowned for his heading ability and his time at Everton." },
  { name: "JOE COLE", hint: "English playmaker who won three Premier League titles with Chelsea after siging from West Ham." },
  { name: "RAY PARLOUR", hint: "English midfielder who played a vital role for Arsenal during their Premier League successes." },
  { name: "DWIGHT YORKE", hint: "Trinidadian striker who formed a legendary partnership with Andy Cole at Manchester United." },
  { name: "GUS POYET", hint: "Uruguayan midfielder who was a key player for Chelsea in the late 1990s." },
  { name: "RUUD GULLIT", hint: "Dutch forward who played for Chelsa before managing them to an FA Cup win in 1997." },
  { name: "JERMAIN DEFOE", hint: "English striker who scored over 160 Premier League goals across his career." },
]

const obscurePlayers = [
  { name: "DEAN HOLDSWORTH", hint: "English forward who formed a prolific strike partnership with Eidur Gudjohnsen at Bolton Wanderers" },
  { name: "MARK SCHWARZER", hint: "Australian goalkeeper who played over 500 Premier League games for Middlesbrough, Fulham, and Chelsea." },
  { name: "FAUSTINO ASPRILLA", hint: "Colombian forward who played for Newcastle United and Parma" },
  { name: "JASON MCATEER", hint: "Irish midfielder who played for Liverpool and Blackburn Rovers." },
  { name: "KEVIN DAVIES", hint: "English striker known for his physicality and leadership at Bolton Wanderers." },
  { name: "IAN HARTE", hint: "Irish left-back with a powerful free-kick, best known for his time at Leeds United." },
  { name: "KURT ZOUMA", hint: "French defender who played for West Ham United, Everton, and Chelsea. Volleyed a cat." },
  { name: "ROBERT GREEN", hint: "English goalkeeper who played for Norwich, West Ham, and QPR." },
  { name: "MIKAEL FORSSELL", hint: "Finnish striker who had productive spells with Birmingham City and Crystal Palace." },
  { name: "BRIAN DEANE", hint: "English striker who scored the first-ever Premier League goal in 1992." },
  { name: "TOMASZ RADZINSKI", hint: "Canadian striker who played for Everton and Fulham." },
  { name: "CRAIG BELLAMY", hint: "Welsh forward who played for Liverpool, Manchester City, and Newcastle United." },
  { name: "DEAN ASHTON", hint: "English striker who showed promise at West Ham before retiring early due to injury." },
  { name: "TREVOR SINCLAIR", hint: "English winger known for his time at West Ham and QPR." },
  { name: "STEPHANE HENCHOZ", hint: "Swiss defender who formed a solid partnership with Sami Hyypia at Liverpool." },
  { name: "PAUL DICKOV", hint: "Scottish striker best remembered for his time at Manchester City and Leicester." },
  { name: "MATTHEW UPTON", hint: "English center-back who played for West Ham and Birmingham City." },
  { name: "PETER LOVENKRANDS", hint: "Danish forward who had successful spells at Rangers and Newcastle United." },
  { name: "LEE CARSLEY", hint: "Irish midfielder known for his consistency at Everton." },
  { name: "SHAY GIVEN", hint: "Irish goalkeeper who was a rock at Newcastle United for over a decade." },
  { name: "PHIL JAGIELKA", hint: "English defender who was Everton's captain for several seasons." },
  { name: "DARREN FLETCHER", hint: "Scottish midfielder who was a reliable presence for Manchester United." },
  { name: "STEWART DOWNING", hint: "English winger who played for Middlesbrough, Aston Villa, and Liverpool." },
  { name: "STEVE STONE", hint: "English midfielder known for his industrious style, playing for Nottingham Forest." },
  { name: "RICHARD DUNNE", hint: "Irish defender who was a stalwart for Manchester City and Aston Villa." },
  { name: "SCOTT PARKER", hint: "English midfielder known for his tenacity and spells at West Ham, Newcastle, and Tottenham." },
  { name: "CHRIS KIRKLAND", hint: "English goalkeeper who played for Wigan and Liverpool." },
  { name: "LUCAS NEILL", hint: "Australian defender who captained West Ham and also played for Blackburn." },
  { name: "MARK PEMBRIDGE", hint: "Welsh midfielder who played for Fulham and Everton." },
  { name: "CARLTON COLE", hint: "English striker who spent much of his career at West Ham United." },
  { name: "JULIO ARCA", hint: "Argentinian midfielder who played for Sunderland and Middlesbrough." },
  { name: "LEE BOWYER", hint: "English midfielder known for his combative style at Leeds United and Newcastle." },
  { name: "GEORGE BOATENG", hint: "Dutch midfielder who played for Aston Villa and Middlesbrough." },
  { name: "SHOLA AMEOBI", hint: "Nigerian forward who was a long-serving player at Newcastle United." },
  { name: "ATTILO LOMBARDO", hint: "Italian winger who played for Crystal Palace. Won the Champions League with Juventus" },
  { name: "ANDY JOHNSON", hint: "English striker known for his goal-scoring at Birmingham City, Crystal Palace and Everton." },
  { name: "KEVIN CAMPBELL", hint: "English striker who helped Everton avoid relegation in the late 1990s." },
  { name: "PHIL NEVILLE", hint: "English utility player who won Premier League titles with Manchester United and later played for Everton." },
  { name: "STEVE FINNAN", hint: "Irish right-back who was part of Liverpool's 2005 Champions League-winning side." },
  { name: "CLINT DEMPSEY", hint: "American forward who had successful spells at Fulham and Tottenham." },
  { name: "PAUL ROBINSON", hint: "English goalkeeper who played for Leeds United, Tottenham, and Blackburn." },
  { name: "JONATHAN WOODGATE", hint: "English center-back who played for Leeds, Newcastle, Real Madrid and Tottenham." },
  { name: "BOBBY ZAMORA", hint: "English striker who played for West Ham, Fulham, and QPR." },
  { name: "JERMAIN JENAS", hint: "English midfielder who played for Newcastle, Tottenham, and QPR." },
  { name: "MARK NOBLE", hint: "English midfielder known as 'Mr. West Ham' for his loyalty and leadership." },
  { name: "ROBERT HUTH", hint: "German defender who was part of Leicester City's historic title-winning side in 2016." },
  { name: "DAVID MAY", hint: "English defender who was part of Manchester United's treble-winning squad in 1999." },
  { name: "EMMANUEL ADEBAYOR", hint: "Togolese striker who played for Arsenal, Manchester City, and Tottenham." },
  { name: "NIKOS DABIZAS", hint: "Greek center-back who was a key player for Newcastle United." },
  { name: "GRAEME LE SAUX", hint: "English left-back who was a mainstay for Blackburn and Chelsea." },
  { name: "DEAN SAUNDERS", hint: "Welsh striker who played for Aston Villa and Liverpool in the 1990s." },
  { name: "DANNY MURPHY", hint: "English midfielder known for his spells at Liverpool and Fulham." },
  { name: "KEVIN KILBANE", hint: "Irish winger who played for Sunderland, Everton, and Wigan Athletic." },
  { name: "MARCO MATERAZZI", hint: "Italian defender who played a brief stint with Everton early in his career." },
  { name: "JASON WILCOX", hint: "English winger who was part of Blackburn's title-winning team in 1995." },
  { name: "MICHAEL GRAY", hint: "English left-back who was a Sunderland stalwart during their Premier League years." },
  { name: "RICHARD WRIGHT", hint: "English goalkeeper who played for Ipswich, Arsenal, and Everton." },
  { name: "NICK BARMBY", hint: "English midfielder who played for Tottenham, Everton, and Liverpool." },
  { name: "CHRISTIAN BENTEKE", hint: "Belgian striker who starred for Aston Villa before moving to Liverpool and Crystal Palace." },
  { name: "JASON ROBERTS", hint: "Grenadian striker who was a key figure at Wigan Athletic and Blackburn Rovers." },
  { name: "YOSSI BENAYOUN", hint: "Israeli midfielder who played for West Ham, Liverpool, and Chelsea." },
  { name: "ANDREI VORONIN", hint: "Ukrainian striker who played for Liverpool" },
  { name: "KIERAN RICHARDSON", hint: "English midfielder who played for Manchester United, West Brom and Sunderland" },
  { name: "MARCUS BENT", hint: "English striker who played for Ipswich Town, Charlton Athletic and Everton" },
  { name: "KEITH GILLESPIE", hint: "Northern Irish winger who played for Newcastle United and Blackburn Rovers." },
  { name: "JASON EUELL", hint: "Jamaican striker who is Charlton Athletic's record goalscorer in the Premier League" },
  { name: "STEED MALBRANQUE", hint: "French midfielder who played for Fulham, Tottenham and Sunderland" },
  { name: "MOMO SISSOKO", hint: "Malian midfielder who played for Liverpool and Juventus" },
  { name: "YOUNES KABOUL", hint: "French defender who played for Tottenham Hotspur and Sunderland" },
  { name: "OLIVIER DACOURT", hint: "French midfielder who played for Leeds United and Everton" },
  { name: "SANDER WESTERVELD", hint: "Dutch goalkeeper who played for Liverpool in the early 2000s" },
  { name: "PAOLO WANCHOPE", hint: "Costa Rican striker who played for Derby County, West Ham, and Manchester City" },
  { name: "MUZZY IZZET", hint: "Turkish midfielder who formed a formidable partnership with Neil Lennon at Leicester City" },
  { name: "STAN LAZARIDIS", hint: "Australian winger known for his time at Birmingham City" },
  { name: "ALI DIA", hint: "Senegalese forward who famously played one game for Southampton" },
  { name: "ERIC DJEMBA-DJEMBA", hint: "Cameroonian midfielder who played for Manchester United" },
  { name: "JONAS GUTIERREZ", hint: "Argentinian winger who played for Newcastle United" },
  { name: "MARCELINO", hint: "Spanish defender who struggled with injuries at Newcastle United" },
  { name: "BOUDEWIJN ZENDEN", hint: "Dutch midfielder who played for Chelsea, Middlesbrough and Liverpool" },
  { name: "PETER ODEMWINGIE", hint: "Nigerian forward who played for West Bromwich Albion. Infamously tried to force a move to QPR" },
  { name: "JULIANO BELLETTI", hint: "Brazilian defender who played for Chelsea" },
  { name: "JONAS OLSSON", hint: "Swedish defender who played for West Bromwich Albion" },
  { name: "JONAS LUNDE", hint: "Norwegian goalkeeper who played for Wimbledon" },
  { name: "STEPHEN CARR", hint: "Irish right-back who played for Tottenham Hotspur and Birmingham City." },
  { name: "MARLON HAREWOOD", hint: "English striker known for his spells at West Ham and Aston Villa." },
  { name: "DAVID NGOG", hint: "French striker who played for Liverpool and Bolton Wanderers." },
  { name: "IAN WOAN", hint: "English midfielder who played for Nottingham Forest" },
  { name: "LUKE CHADWICK", hint: "English winger who played for Manchester United and Norwich City." },
  { name: "ERIK EDMAN", hint: "Swedish defender who played for Tottenham Hotspur. Scored a famous goal against Liverpool" },
  { name: "ADEL TAARABT", hint: "Moroccan midfielder who played for Queens Park Rangers and Tottenham Hotspur" },
  { name: "DAVID DUNN", hint: "English midfielder who played for Blackburn Rovers and Birmingham City." },
  { name: "MOUSSA DEMBELE", hint: "Belgian midfielder who played for Fulham before moving to Tottenham Hotspur." },
  { name: "CHRISTIAN DAILLY", hint: "Scottish defender who played for West Ham United and Blackburn Rovers." },
  { name: "EL HADJI DIOUF", hint: "Senegalese forward who played for Liverpool, Bolton Wanderers and Blackburn Rovers." },
  { name: "KEVIN NOLAN", hint: "English midfielder and captain at clubs like Bolton and West Ham." },
  { name: "GEOVANNI", hint: "Brazilian attacking midfielder who played for Manchester City and Hull City." },
  { name: "ANTTI NIEMI", hint: "Finnish goalkeeper known for his time at Southampton" },
  { name: "ZOLTAN GERA", hint: "Hungarian midfielder who played for West Bromwich Albion and Fulham." },
  { name: "BRAD GUZAN", hint: "American goalkeeper who played for Aston Villa." },
  { name: "FABRICE MUAMBA", hint: "Congolese-born midfielder who played for Birmingham City and Bolton Wanderers." },
  { name: "DAVID BENTLEY", hint: "English winger known for his time at Blackburn Rovers and Tottenham Hotspur." },
  { name: "CHRITIAN KAREMBEU", hint: "French midfielder who won the World Cup and Champions League before joining Middlesbrough" },
  { name: "NOLBERTO SOLANO", hint: "Peruvian midfielder who played for Newcastle United" },
  { name: "GAVIN MCCANN", hint: "English midfielder who played for Aston Villa and Bolton" },
  { name: "NICKLAS BENDTNER", hint: "Danish forward known for his time at Arsenal and his self-confidence" },
  { name: "ALVARO NEGREDO", hint: "Spanish striker who played for Manchester City and Middlesbrough" },
  { name: "ERIC NEVLAND", hint: "Norwegian forward who played for Fulham" },
  { name: "ANDY HINCHCLIFFE", hint: "English defender who played for Manchester City and Everton" },
  { name: "DARREN ANDERTON", hint: "English midfielder who played for Tottenham Hotspur and Portsmouth" },
  { name: "FRANK LEBOEUF", hint: "French defender who played for Chelsea and won the World Cup" },
  { name: "MIKE NEWELL", hint: "English striker who played for Blackburn Rovers and Everton" },
  { name: "PAUL RIDEOUT", hint: "English striker who scored the winning goal for Everton in the 1995 FA Cup Final" },
  { name: "BENITO CARBONE", hint: "Italian forward who played for Sheffield Wednesday and Bradford City" },
  { name: "DAVID UNSWORTH", hint: "English defender who played for Everton. Scored a lot of penalties" },
  { name: "MICHAEL DUBERRY", hint: "English defender who played for Chelsea and Leeds United" },
  { name: "DOMINIC MATTEO", hint: "Scottish defender who played for Liverpool and Leeds United" },
  { name: "STEVE HARKNESS", hint: "English defender who played for Liverpool" },
  { name: "WARREN BARTON", hint: "English defender who played for Newcastle United" },
  { name: "JIM MAGILTON", hint: "Northern Irish midfielder who played for Southampton and Ipswich Town" },
  { name: "ROD WALLACE", hint: "Scottish forward who played for Leeds United and Rangers" },
  { name: "SLAVEN BILIC", hint: "Croatian defender who played for West Ham United and Everton" },
  { name: "CARLO CUDICINI", hint: "Italian goalkeeper who played for Chelsea and Tottenham Hotspur" },
  { name: "QUINTON FORTUNE", hint: "South African midfielder who played for Manchester United" },
  { name: "MARK BOSNICH", hint: "Australian goalkeeper who played for Aston Villa and Manchester United" },
  { name: "PAPISS CISSE", hint: "Senegalese striker who scored some spectacular goals for Newcastle United" },
  { name: "JOHN OSTER", hint: "Welsh winger who played for Everton and Reading" },
  { name: "WILFRIED BONY", hint: "Ivorian striker who played for Swansea City and Manchester City" },
  { name: "TOMAS ROSICKY", hint: "Czech midfielder who played for Arsenal and Borussia Dortmund" },
  { name: "MORITZ VOLZ", hint: "German defender who played for Fulham and Ipswich Town" },
  { name: "PAUL KONCHESKY", hint: "English left-back who played for several Premier League clubs" },
  { name: "JAMES BEATTIE", hint: "English striker who played for Southampton and Everton" },
  { name: "PIERRE VAN HOOIJDONK", hint: "Dutch striker who played for Nottingham Forest and Celtic" },
  { name: "SEBASTIEN BASSONG", hint: "Cameroonian defender who played for Newcastle and Tottenham" },
  { name: "STEVEN PIENAAR", hint: "South African midfielder who played for Everton and Tottenham" },
  { name: "NIKO KRANJCAR", hint: "Croatian midfielder who played for Portsmouth and Tottenham" },
  { name: "IVAN CAMPO", hint: "Spanish midfielder who played for Bolton Wanderers and Real Madrid" },
  { name: "JOHN CAREW", hint: "Norwegian striker who played for Aston Villa and West Ham" },
  { name: "MAURO ZARATE", hint: "Argentinian forward who played for Birmingham City and West Ham" },
  { name: "LUKAS PODOLSKI", hint: "German forward who played for Arsenal. Owns a kebab shop" },
  { name: "THOMAS GRAVESEN", hint: "Danish midfielder who played for Everton and Real Madrid" },
  { name: "GARY BREEN", hint: "Irish defender who played for Coventry City and Sunderland" },
  { name: "NOEL WHELAN", hint: "English forward who played for Coventry City and Middlesbrough" },
  { name: "THOMAS BROLIN", hint: "Swedish forward who played for Leeds United" },
  { name: "MATT ELLIOTT", hint: "Leicester City's captain during their League Cup triumphs in 1997 and 2000" },
  { name: "HENRI CAMARA", hint: "Senegalese forward who played for Wigan Athletic" },
  { name: "SHAUN GOATER", hint: "Bermudian forward who played for Manchester City" },
  { name: "HERMANN HREIDARSSON", hint: "Icelandic defender who played for several Premier League clubs, including Charlton and Portsmouth." },
  { name: "DAVID WEIR", hint: "Scottish defender who had a long career at Everton." },
  { name: "IAN TAYLOR", hint: "English midfielder who became a fan favorite at Aston Villa." },
  { name: "GEOFF HORSFIELD", hint: "English striker known for his determination at Birmingham City and West Brom." },
  { name: "GEORGI KINKLADZE", hint: "Georgian midfielder known for his time at Manchester City" },
  { name: "GARETH FARRELLY", hint: "Irish midfielder who played for Everton and Bolton" },
  { name: "PETER NDLOVU", hint: "Zimbabwean forward who played for Coventry City" },
  { name: "MATTHEW UPSON", hint: "English defender known for his time at Birmingham City" },
  { name: "MARCO BOOGERS", hint: "Dutch striker who once hid in a caravan after being sent off" },
  { name: "PAPA BOUBA DIOP", hint: "Senegalese midfielder who played for Fulham. Scored the first goal of the 2002 World Cup" },
  { name: "PASCAL CHIMBONDA", hint: "French defender who played for Tottenham Hotspur, Sunderland and Wigan Athletic" },
  { name: "SERHIY REBROV", hint: "Ukrainian striker who flopped at Tottenham despite a prolific partnership with Andriy Shevchenko at Dynamo Kyiv" },
  { name: "KLEBERSON", hint: "Brazilian midfielder who won the World Cup in 2002 before joining Manchester United" },
  { name: "FABIO ROCHEMBACK", hint: "Brazilian midfielder who played for Barcelona, Sporting Lisbon and Middlesbrough" },
  { name: "DAVID BELLION", hint: "French striker who had an underwhelming spell at Manchester United in the early 2000s" },
  { name: "IGOR STEPANOVS", hint: "Latvian defender who Arsenal signed as cover but looked out of his depth in the Premier League" },
  { name: "PHILLIPE SENDEROS", hint: "Swiss defender who struggled at Arsenal before spells with Fulham and Aston Villa" },
  { name: "PER KROLDRUP", hint: "Danish defender who Everton signed for £5m in 2005 but made just one appearance before being sold" },
  { name: "BOSKO BALABAN", hint: "Croatian striker who Aston Villa signed for £5.8m in 2001 but made just nine appearances" },
  { name: "CHRIS BART-WILLIAMS", hint: "Midfielder who was a regular for Nottingham Forest in the 1990s but struggled after a big-money move to Sheffield Wednesday" },
  { name: "DARIUS VASSELL", hint: "English striker who scored on his England debut. Played for Aston Villa and Manchester City" },
  { name: "STEPHEN IRELAND", hint: "Irish midfielder who was named Manchester City's Player of the Year in 2009" },
  { name: "KAREL POBORSKY", hint: "Czech winger who scored a memorable chip at Euro 96 before joining Manchester United" },
  { name: "BRUNO CHEYROU", hint: "French midfielder who Gerard Houllier claimed would be the 'new Zidane' when he joined Liverpool" },
  { name: "CHRISTOPHE DUGARRY", hint: "French forward who won the World Cup in 1998 before joining Birmingham City" },
  { name: "SALIF DIAO", hint: "Senegalese midfielder who joined Liverpool after impressing at the 2002 World Cup but struggled in the Premier League" },
  { name: "SEAN DUNDEE", hint: "South African striker who Liverpool signed for £2m in 1998 but made just five appearances" },
  { name: "JOZY ALTIDORE", hint: "American striker who scored just one Premier League goal during spells with Hull City and Sunderland" },
  { name: "ANDRE SANTOS", hint: "Brazilian left-back who Arsenal signed for £6.2m in 2011 but was defensively suspect and once swapped shirts with Robin van Persie at half-time" },
  { name: "TORBEN PIECHNIK", hint: "Danish defender who joined Liverpool in 1992 but made a series of high-profile errors" },
  { name: "JORDI CRUYFF", hint: "Son of legend who played for Manchester United and Barcelona" },
  { name: "KOSTAS MITROGLOU", hint: "Greek striker who Fulham signed for a club-record £12m in 2014 but scored just once" },
  { name: "CORRADO GRABBI", hint: "Italian striker who Blackburn Rovers signed for £6.75m in 2001 but failed to score a single goal" },
  { name: "MICHAEL RICKETTS", hint: "English striker who earned one England cap while at Bolton Wanderers but then faded into obscurity" },
  { name: "ADRIAN MUTU", hint: "Romanian striker who impressed at Chelsea before being sacked for failing a drugs test" },
  { name: "ADE AKINBIYI", hint: "Much-travelled Nigerian striker who had spells with Norwich City, Leicester City and Sheffield United" },
  { name: "ED DE GOEY", hint: "Dutch goalkeeper who played for Chelsea and Stoke City" },
  { name: "ERIC MEIJER", hint: "Dutch striker who had a brief spell with Liverpool in the late 1990s" },
  { name: "JEAN CLAUDE DARCHEVILLE", hint: "French striker who had brief spells with Nottingham Forest and Rennes in the late 1990s" },
  { name: "ERIK NEVLAND", hint: "Norwegian striker who had two spells with Manchester United in the late 1990s but made just one Premier League appearance" },
  { name: "NICLAS JENSEN", hint: "Danish defender who had brief spells with Manchester City and Borussia Dortmund in the late 1990s" },
  { name: "TITI CAMARA", hint: "Guinean striker who had a successful spell with Liverpool in 1999-2000, scoring 10 goals in 37 appearances" },
  { name: "TORRE ANDRE FLO", hint: "Norwegian striker who had a successful spell with Chelsea in the late 1990s and early 2000s" },
  { name: "CARSTEN JANCKER", hint: "German striker who had a brief loan spell with Barnsley in 1998-99 but failed to score in six appearances" },
]

async function seedPlayers() {
  console.log('Starting player seed...')
  
  const batch = writeBatch(db)
  let count = 0

  const addPlayersToCategory = (players: Array<{name: string, hint: string}>, category: 'modern' | 'legend' | 'obscure') => {
    players.forEach((player) => {
      const docId = player.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
      const playerRef = doc(db, 'players', docId)
      
      batch.set(playerRef, {
        name: player.name,
        hint: player.hint,
        category,
        isActive: true,
        createdAt: serverTimestamp(),
      })
      count++
    })
  }

  addPlayersToCategory(modernPlayers, 'modern')
  addPlayersToCategory(legendPlayers, 'legend')
  addPlayersToCategory(obscurePlayers, 'obscure')

  console.log(`Preparing to seed ${count} players...`)
  console.log(`- Modern: ${modernPlayers.length}`)
  console.log(`- Legend: ${legendPlayers.length}`)
  console.log(`- Obscure: ${obscurePlayers.length}`)

  await batch.commit()
  console.log('✅ Players seeded successfully!')
}

seedPlayers().catch(console.error)
